### PR TITLE
Feature/minor corrections

### PR DESCRIPTION
**Pull request by joranvar**
Hello,

While reading the code, looking for a place to extend/customize jira-org, I felt like fixing up some whitespace, minor misspellings and warnings from flycheck.

Pick and choose (or merge *ALL* the things) if you feel like it! :)

### CODE REVIEW

**Comment by baohaojun** [comment]
Hi, the patches looks great to me, and I have tested it, things are working.

But I have noticed that you prefer to use Tab instead of all spaces characters. This is in conflict with my style and the style recommended in https://github.com/bbatsov/emacs-lisp-style-guide, so can you please consider replace the tabs with spaces?

Thanks!

**Comment by joranvar** [comment]
Hi!

My bad, I did not check this. I presumed that whitespace-cleanup would convert tabs to spaces (my preference also). Will update-and-force-push when I'm back at home!

**Comment by joranvar** [comment]
This should take care of those tabs. Thanks you for pointing this out to me, I changed my settings for other projects as well.

**Comment by baohaojun** [comment]
Merged. Thank you very much for doing so much!

**Comment by joranvar** [comment]
It was my pleasure!

**Pull request merged**
